# Generated by Django 5.2.8 on 2026-03-12 15:05

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_expert_score_user_profile_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
