# Generated by Django 5.2.8 on 2026-03-12 15:05

from pgvector.django import VectorField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_questionvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='embedding',
            field=VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
