# Generated by Django 5.0.6 on 2026-07-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('question_asked', 'Question Asked'), ('question_answered', 'Question Answered'), ('message_sent', 'Message Sent'), ('achievement_unlocked', 'Achievement Unlocked'), ('bookmark_added', 'Bookmark Added'), ('upvote_given', 'Upvote Given'), ('helper_joined', 'Helper Joined'), ('session_closed', 'Session Closed')], max_length=50),
        ),
    ]
